{% set version = '0.1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-safetensors
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/safetensors_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/safetensors/safetensors_{{ version }}.tar.gz
  sha256: 776e7f71f19e0f1e51964a48502528be6eb6515ffd610ca862ff9da6852f6f77

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-cli
    - r-jsonlite
    - r-rlang
  run:
    - r-base
    - r-r6
    - r-cli
    - r-jsonlite
    - r-rlang

test:
  commands:
    - $R -e "library('safetensors')"           # [not win]
    - "\"%R%\" -e \"library('safetensors')\""  # [win]

about:
  home: https://mlverse.github.io/safetensors/
  dev_url: https://github.com/mlverse/safetensors
  license: MIT
  summary: A file format for storing tensors that is secure (doesn't allow for code execution),
    fast and simple to implement. 'safetensors' also enables cross language and cross
    frameworks compatibility making it an ideal format for storing machine learning
    model weights.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
